name: ðŸ«£ Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      VARIANT: assembleWebsiteFullDebug
    steps:
    - name: ðŸ¥ Checkout
      uses: actions/checkout@v6
    - name: â˜•ï¸ JDKv17
      uses: actions/setup-java@v5
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle
    - name: âš¡ï¸ +x gradlew
      run: chmod +x gradlew
    - name: ðŸŽª Secrets
      if: success()
      # TODO: override iff it doesn't exist
      # developers.google.com/android/guides/google-services-plugin#adding_the_json_file
      run: |
        mkdir -p app/src/debug
        echo "${GSCV_TEST_JSON}" > app/src/debug/google-services.json
        # expected: l:29 w:45 m:691
        wc -lwm app/src/debug/google-services.json
        if [ -z "$GSCV_TEST_JSON" ]; then
          echo "VARIANT=assembleFdroidFullDebug" >> "$GITHUB_ENV"
        fi
      env:
        GSCV_TEST_JSON: ${{ secrets.GOOGLE_SERVICES_TEST_JSON }}
    - name: ðŸš‚ Assemble
      if: success()
      run: |
        ./gradlew lint
        ./gradlew \
          ${VARIANT} \
          --info \
          --warning-mode all
      env:
        VARIANT: ${{ env.VARIANT }}
